### ISSUE TITLE
AFK/HC to organize VCless runs

### ISSUE THREAD

**Issue by sjkd23** [ToogaInc/ToogaBooga#243]
We want to change 'Event Leader' to 'Event Organizer'.

The Headcount can probably be the same as normal, except it would advertise it being 'VCless'.

The AFK check would make it so people have to react to get the location, meaning we can still parse people under-reqs and not 'part of the raid'.

**Comment by Deaththth** [comment]
Extra Adjustements:
Give early loc during pre-afk to priority reacts, reveal loc to everyone WHO reacts to join with a button once afk starts, logs who reacted to join and reacted to the special reactions, gives a logging window that has that info to compare a /who and then log a completion to everyone which made it.

**Comment by Deaththth** [comment]
Alright to line the feature out in a way more clear at request of a dev:
- Section based permission on configafk to allow a section put up VCless afk
- Extra Option when starting afk or converting alongside creating a new vc and using an existing vc
- AFK without a vc, but instead a new JOIN button
- Pressing the JOIN button logs the player who joins the raid and gives them location
- Logging in the end gives option to log who is in the /who or people who reacted to join
- The info on who joined can be used for the VCless parse command: https://github.com/ToogaInc/ToogaBooga/issues/266

**Comment by dmansdman** [comment]
Added new afk type: vcless afk
- configurable on a per-section basis
- chosen from headcount conversion or afkcheck command
- earlys get loc through usual means (dm, ephemeral reply)
- raiders can join using the "join" button after pre-afk is over (like polarity
- raiders can no longer join once raid is started, unless RL unlocks the raid
- raider cap is same as vc cap
- parse is based on users who joined with button and earlies

Added parsevcless
- user selects from an active vcless afk
- does not work locally yet due to connection issues with api. please investigate
